apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-network
  namespace: default
spec:
  config: |-
    {
            "cniVersion": "0.3.1", 
            "name": "localnet2",
            "type": "ovn-k8s-cni-overlay", 
            "topology": "localnet", 
            "netAttachDefName": "default/vm-network" 
    }
