apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br0-ext
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: '' 
  desiredState:
    interfaces:
    - name: ovs-br0-ext 
      description: |-
        A dedicated ovs bridge for external VM traffic
      type: ovs-bridge
      state: up
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: false
        port:
        - name: enp8s0 
    ovn:
      bridge-mappings:
      - localnet: vm-network
        bridge: ovs-br0-ext
        state: present
