apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged 
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
  name: openshift-file-integrity
