apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  multiCloudGateway:
    endpoints:
      minCount: 1
      maxCount: 2
  enableCephTools: true
  manageNodes: false
  resources:
   mds:
     limits:
       cpu: "3"
       memory: "8Gi"
     requests:
       cpu: "0.5"
       memory: "500Mi"
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
  - config: {}
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "100Gi"
        storageClassName: localblock
        volumeMode: Block
      status: {}
    name: ocs-deviceset
    placement: {}
    preparePlacement: {}
    replica: 3
    resources:
     limits:
       cpu: "2"
       memory: "5Gi"
     requests:
       cpu: "0.5"
       memory: "500Mi"
