apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  multiCloudGateway:
    reconcileStrategy: ignore # <- Set this to ignore (disable) or manage (enable) Multicloud Object Gateway
    endpoints:
      minCount: 1
      maxCount: 2
  enableCephTools: false
  managedResources: 
    cephFilesystems:
      reconcileStrategy: manage # <- Set this to ignore (disable) or manage (enable) Ceph Filesystem
    cephObjectStores:
      reconcileStrategy: ignore # <- Set this to ignore (disable) or manage (enable) Ceph RGW
  resources:
   mds:
     limits:
       cpu: "3"
       memory: "8Gi"
     requests:
       cpu: "500m"
       memory: "500Mi"
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
  - config: {}
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "100Gi"
        storageClassName: localblock
        volumeMode: Block
      status: {}
    name: ocs-deviceset
    placement: {}
    preparePlacement: {}
    replica: 3
    resources:
     limits:
       cpu: "2"
       memory: "5Gi"
     requests:
       cpu: "500m"
       memory: "500Mi"
