apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nmstate-operator
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: nmstate
    repoURL: https://github.com/pharriso/ocp_infra_gitops.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    retry:
      limit: 10
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
