apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv-ocp
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ipAddressPools:
    - ip-addresspool-ocp
