apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: engine
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  availabilityConfig: Basic
