apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: stable-2.8
  installPlanApproval: Automatic
  name: multicluster-engine
