apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  channel: stable-2.x
  name: multicluster-engine
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
